# Use Docker-based container (instead of OpenVZ)
sudo: false
language: scala
scala:
- 2.13.6
jdk:
- openjdk13

# codecov
script:
  - sbt clean coverage test
  - sbt coverageReport
  - sbt coverageAggregate

before_install:
- pip install --user codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)

# http://www.scala-sbt.org/0.13/docs/Travis-CI-with-sbt.html
# These directories are cached to S3 at the end of the build
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/

before_cache:
  # Tricks to avoid unnecessary cache updates
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
