addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"           % "2.0.0")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"          % "1.5.1")
//addSbtPlugin("org.wartremover"                    % "sbt-wartremover"        % "2.1.1")
//addSbtPlugin("com.thoughtworks.sbt-best-practice" % "sbt-best-practice"      % "latest.release")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.3")
addSbtPlugin("com.jsuereth"   % "sbt-pgp"      % "1.1.2")
