addSbtPlugin("org.scalastyle" %% "scalastyle-sbt-plugin" % "1.0.0")
addSbtPlugin("org.scalameta"  % "sbt-scalafmt"           % "2.4.2")
addSbtPlugin("org.scoverage"  % "sbt-scoverage"          % "1.8.2")
//addSbtPlugin("org.wartremover"                    % "sbt-wartremover"        % "2.1.1")
//addSbtPlugin("com.thoughtworks.sbt-best-practice" % "sbt-best-practice"      % "latest.release")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "3.9.7")
addSbtPlugin("com.jsuereth"   % "sbt-pgp"      % "2.1.1")
